[package]
name = "cache_loader_async"
version = "0.1.0"
authors = ["Alexander Becker <abecker@bitflow.dev>", "Spencer Sharkey <spencer@sf-n.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.3.0", features = ["full"] }
futures = "0.3.14"