name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
          - os: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build
    - name: Run tests no-features
      run: cargo test
    - name: Run tests lru-feature
      run: cargo test --features lru-cache
    - name: Run tests ttl-feature
      run: cargo test --features ttl-cache
    - name: Run tests all-features
      run: cargo test --features lru-cache,ttl-cache